work around issue with python/PyQt breaking with multiple inheritance which gives this:
Traceback (most recent call last):
  File "wb_git_main.py", line 69, in <module>
    sys.exit( main( sys.argv ) )
  File "wb_git_main.py", line 53, in main
    app = wb_git_app.WbGit_App( argv )
  File "/home/barry/wc/git/git-workbench/Source/Git/wb_git_app.py", line 194, in __init__
    self.main_window = wb_git_main_window.WbGitMainWindow( self )
  File "/home/barry/wc/git/git-workbench/Source/Git/wb_git_main_window.py", line 64, in __init__
    QtWidgets.QMainWindow.__init__( self )
TypeError: __init__() missing 1 required positional argument: 'image_store'